core_cagnotte_utilisateur:
    resource: "@CoreCagnotteBundle/Controller/utilisateurController.php"
    type:     annotation

core_cagnotte:
    resource: "@CoreCagnotteBundle/Resources/config/routing.yml"
    prefix:   /cagnotte

app:
    resource: '@AppBundle/Controller/'
    type: annotation
