fournisseur_index:
    path:     /
    defaults: { _controller: "CoreCagnotteBundle:Fournisseur:index" }
    methods:  GET

fournisseur_show:
    path:     /{id}/show
    defaults: { _controller: "CoreCagnotteBundle:Fournisseur:show" }
    methods:  GET

fournisseur_new:
    path:     /new
    defaults: { _controller: "CoreCagnotteBundle:Fournisseur:new" }
    methods:  [GET, POST]

fournisseur_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreCagnotteBundle:Fournisseur:edit" }
    methods:  [GET, POST]

fournisseur_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreCagnotteBundle:Fournisseur:delete" }
    methods:  DELETE
