utilisateur_index:
    path:     /
    defaults: { _controller: "CoreCagnotteBundle:utilisateur:index" }
    methods:  GET

utilisateur_show:
    path:     /{id}/show
    defaults: { _controller: "CoreCagnotteBundle:utilisateur:show" }
    methods:  GET

utilisateur_new:
    path:     /new
    defaults: { _controller: "CoreCagnotteBundle:utilisateur:new" }
    methods:  [GET, POST]

utilisateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreCagnotteBundle:utilisateur:edit" }
    methods:  [GET, POST]

utilisateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreCagnotteBundle:utilisateur:delete" }
    methods:  DELETE
