core_cagnotte_fournisseur:
    resource: "@CoreCagnotteBundle/Resources/config/routing/fournisseur.yml"
    prefix:   /fournisseur

core_cagnotte_homepage:
    path:     /
    defaults: { _controller: CoreCagnotteBundle:Default:index }
