
core_cagnotte_produit:
    resource: "@CoreCagnotteBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

core_cagnotte_categorie:
    resource: "@CoreCagnotteBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

core_cagnotte_fournisseur:
    resource: "@CoreCagnotteBundle/Resources/config/routing/fournisseur.yml"
    prefix:   /fournisseur

core_cagnotte_utilisateur:
    resource: "@CoreCagnotteBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur

core_cagnotte_homepage:
    path:     /
    defaults: { _controller: CoreCagnotteBundle:Default:index }
