core_cagnotte_categorie:
    resource: "@CoreCagnotteBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

core_cagnotte_homepage:
    path: /
    defaults: {_controller: CoreCagnotteBundle:Default:index}